const char * sgb_instr_names_table[] = {
        "Sine 0",
        "Sine 1",
        "Sine 2",
        "Sine 3",
        "Sine 4",
        "Sine 5",
        "Sine 6",
        "Sine 7",
        "Bass 00",
        "Bass 01",
        "Bass 02",
        "Bass 03",
        "Bass 10",
        "Bass 11",
        "Bass 12",
        "Bass 13",
        "Guitar 0 / Harp",
        "Guitar 1 (Plucked)",
        "Guitar 2 (Picked)",
        "Guitar 3 / Sax",
        "Keys 00",
        "Keys 01",
        "Keys 02",
        "Keys 03 / Whistle",
        "Keys 10 / E-Piano",
        "Keys 11",
        "Keys 12 / E-Piano 2",
        "Organ",
        "Strings 0",
        "Strings 1 (Soft)",
        "Strings 2",
        "Choir 00 (bugs?)",
        "Choir 01 (bugs?)",
        "Choir 10 (bugs?)",
        "Choir 11 (bugs?)",
        "Xylo 0",
        "Xylo 1 / lo-pi organ",
        "Xylo 2",
        "Xylo 3",
        "Brass 00",
        "Brass 01",
        "Brass 10",
        "Trumpet 0",
        "Trumpet 1",
        "Trumpet 2",
        "Trumpet 3",
        "Bassoon 0",
        "Bassoon 1",
        "Flute 0",
        "Bass dr ",
        "Cl. hihat",
        "Open hihat ",
        "Snare 0",
        "Snare 1",
        "Tom",
        "Clap",
        "SFX Jet 0",
        "SFX Jet 1",
        "SFX Noise",
        "SFX Glass",
        "SFX Shot",
        "SFX Water",
        "SFX Wind",};

const char * sgb_song_names_table[] = {
    "bgm1: Simple Blues",
    "bgm2: note len test",
    "Unused"};

